---
title: "Monthly Indoor CO2 Summary"
format: html
editor: visual
---

# The monthly indoorCO2map.com summary

```{r}
library(ggplot2)
library(tidyplots)
library(gt)
```

```{r}

buildings_wide_df <- autocruller::ac_get_co2("web") |> 
    dplyr::filter(dplyr::between(
        lubridate::floor_date(date, unit = "month"),
        lubridate::today() |> lubridate::floor_date(unit = "month"),
        lubridate::today() |> lubridate::ceiling_date(unit = "month")
    )) |> 
        dplyr::mutate(type = "building")
buildings_long_df <- autocruller::ac_unnest_longer(buildings_wide_df)

transit_long_df <- autocruller::ac_get_co2("transit")|> 
        dplyr::mutate(type = "transit")
# everything_df <- dplyr::bind_rows()
```

## Buildings

This month there were `r nrow(buildings_wide_df)` measurements of `length(unique(buildings_wide_df$combined_id))` unique buildings. 

```{r}
countries_count <- 
buildings_wide_df |> 
    dplyr::group_by(countryname) |> 
    dplyr::count() |> 
    tidyr::drop_na() |> 
    sf::st_drop_geometry() |> 
    dplyr::ungroup()
countries_count[order(countries_count$n, decreasing = TRUE),] |> 
    # dplyr::arrange(n) 
    gt() |> 
    tab_header(title = "Top countries")
    
```

## Transit

## Everything

Comine both long datasets and then make a beeswarm comparing buildings to transit
```{r}
buildings_long_df |> 
    dplyr::group_by(obs_number) |> 
    dplyr::summarise(
        co2_median = median(co2readings, na.rm = TRUE),
        ventilation = dplyr::first(ventilation)
        ) |> 
tidyplot(
         x = ventilation, 
         y = co2_median,
         color = co2_median) |> 
  # add_violin() |>
  add_data_points_beeswarm(size = 3) |> 
  adjust_y_axis(transform = "log2") |> 
  adjust_size(width = NA, height = NA, unit = "cm") |> 
  adjust_font(fontsize = 16) |> 
  adjust_x_axis_title("Ventilation system on?") |> 
  adjust_y_axis_title("CO2 ppm average") |> 
  remove_legend() |> 
  adjust_title("CO2 Averages at music venues") |> 
  adjust_caption("Data from indoorCO2map.com")
```